from pathlib import Path

ROOT_DIR = Path(__file__).parent.parent.parent
FILES_DIR = ROOT_DIR / "files"
WINDOW_ICON_PATH = FILES_DIR / "barcode-scan.png"


MODULO10_VALOR_EFETIVO = 6
MODULO10_QUANTIDADE_MOEDA = 7
MODULO11_VALOR_EFETIVO = 8
MODULO11_QUANTIDADE_MOEDA = 9


CODIGO_ARRECADAO = 8
